### ISSUE TITLE
导入Eclipse并更新maven后，niubi-job-cluster的pom.xml报错

### ISSUE THREAD

**Issue by wzx-xle** [xiaolongzuo/niubi-job#13]
IDE：Eclipse Java EE IDE for Web Developers Mars.2 Release (4.5.2)

**现象**：
    将整个项目通过maven导入，并更新项目后，niubi-job-cluster子模块的pom.xml报错：
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-antrun-plugin:1.8:run (execution: prepared-build, phase: test-compile)

**分析原因**：
    表示m2e在其执行maven的生命周期管理时没有定义该插件，所以提示出错

**解决**：
1、进入Window—>Preferences—>Maven配置，进入Lifecycle Mapping设置项
2、点击 【Open workspace lifecycle mappings metadata】，在编辑器打开了配置文件
3、复制如下的xml进入，并保存：
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
    <pluginExecutions>
    
        <pluginExecution>
            <pluginExecutionFilter>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <goals>
                    <goal>run</goal>
                </goals>
                <versionRange>[1.8,)</versionRange>
            </pluginExecutionFilter>
            <action>
                <ignore />
            </action>
        </pluginExecution>
        
    </pluginExecutions>
</lifecycleMappingMetadata>
```
4、重新打开Lifecycle Mapping设置项，点击【Reload workspace lifecycle mappings metadata】，并重新更新项目即可

**参考**：
http://www.cnblogs.com/hzhuxin/archive/2012/06/17/2552998.html

**Comment by xiaolongzuo** [comment]
已经merge。
