### ISSUE TITLE
How to update the jar file?

### ISSUE THREAD

**Issue by dengcb179** [xiaolongzuo/niubi-job#3]
If the job jar file updated, how to do that?

**Comment by xiaolongzuo** [comment]
Upload the new jar file with a new file name(etc. my-app-1.1.jar), and restart the job using the new jar file .It likes below.
![image](https://cloud.githubusercontent.com/assets/5348137/12636430/d8835944-c5c7-11e5-87c9-7c59c16bcbcd.png)
